gravitee-io/gravitee-expression-language

src/test/java/io/gravitee/el/spel/SpelTemplateEngineTest.java
Just adding a single test case to show how JsonPath expressions that return arrays can be used in a SPeL expression.
=> Add unit test to demonstrate SPeL/JsonPath expressions that can be useful for handling OpenId introspection data.

src/main/resources/whitelist
Authorize `EvaluableSSLPrincipal` class to be evaluated in TemplateEngine
gravitee-io/issues#5322
=> feat: allow access to SSL attributes in EL TemplateEngine

pom.xml, src/main/java/io/gravitee/el/spel/context/ReadOnlyMapAccessor.java, src/main/java/io/gravitee/el/spel/context/SecuredEvaluationContext.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
It would be simpler to access to map value with dot syntax like `{#context.attributes.api}`
https://github.com/gravitee-io/issues/issues/7228
=> feat: improve map access with dot

src/main/java/io/gravitee/el/spel/context/HttpHeadersPropertyAccessor.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7283
Until 3.15.0, the implementation of `headers.getAll` returned null if a header is not sent in the request.
Since 3.15.0, it returns an empty list. But it's a breaking change for every users that test headers in their expression language condition.
This PR fix the regression.
=> template evaluation on missing headers

src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
When testing jupiter debug mode, it appears that if the condition evaluated is malformated an exception is thrown out of reactive contexte.
---
- use it directly by updating your project with version: `1.10.1-jupiter-fix-el-expression-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.10.1-jupiter-fix-el-expression-SNAPSHOT/gravitee-expression-language-1.10.1-jupiter-fix-el-expression-SNAPSHOT.zip)
=> fix(spel): catch parsing exception and return Maybe on error

pom.xml, src/main/java/io/gravitee/el/spel/context/HttpHeadersPropertyAccessor.java, src/main/resources/whitelist, src/test/java/io/gravitee/el/spel/context/HttpHeadersPropertyAccessorTest.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7812
- Improve `canRead` method doing some type checking
- Enrich whitelist to take benefit from `MultiValueMap` and `io.gravitee.gateway.api.http.HttpHeaders`
⚠️ Waiting for https://github.com/gravitee-io/gravitee-gateway-api/pull/118 to be merged 
---
- use it directly by updating your project with version: `1.9.3-issues-7812-retro-headers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.9.3-issues-7812-retro-headers-SNAPSHOT/gravitee-expression-language-1.9.3-is …
=> fix: restore HTTP headers backward compatibility

src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/EvaluableRequest.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
gravitee-io/issues#8217
---
- use it directly by updating your project with version: `1.9.5-2359-fix-regex-quantifiers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.9.5-2359-fix-regex-quantifiers-SNAPSHOT/gravitee-expression-language-1.9.5-2359-fix-regex-quantifiers-SNAPSHOT.zip)
=> fix: resolve regex with quantifiers

pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java
**Issue**
https://github.com/gravitee-io/issues/issues/8229
---
- use it directly by updating your project with version: `1.11.0-feat-endpoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.11.0-feat-endpoint-SNAPSHOT/gravitee-expression-language-1.11.0-feat-endpoint-SNAPSHOT.zip)
=> feat: use higher level HttpExecutionContext for TemplateProvider

pom.xml, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/main/java/io/gravitee/el/spel/TemplateParserContext.java, src/main/resources/whitelist, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
Before this fix, `{` is the expression prefix of the EL engine.
As this character can be in regular strings, out of any expression language, they are replaced with `{'{'}` which is a interpreted as a list of one `{` character during expression evaluation.
That causes problems when `{` is, as a string, inside a expression language function parameter, for example `{#request.pathInfo.matches('/[A-Z]{2}')}` : the `{2}` shouldn't be escaped.
With this fix, `{#` is the expression prefix of the EL engine.
EL prefixes from user input : `{#`, `{(`, or `{T` are replaced by `{##`, `{#(`, or `{#T`. Regular `{` characters aren't interpreted as expression prefixes by EL SpelExpressionParser
**Issue**
https://github.com/gravitee-io/issues/issues/8367
---
🚀 A …
=> fix: properly handle brackets in evaluated expressions

CHANGELOG.md, pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java, src/main/java/io/gravitee/el/spel/SpelExpressionParser.java
**Issue**
https://github.com/gravitee-io/issues/issues/8479
Merge `1.9.x` into `master`
---
- use it directly by updating your project with version: `1.11.2-merge-1-9-x-into-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.11.2-merge-1-9-x-into-master-SNAPSHOT/gravitee-expression-language-1.11.2-merge-1-9-x-into-master-SNAPSHOT.zip)
=> Merge `1.9.x` into `master`

pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/7990
---
- use it directly by updating your project with version: `2.0.0-chore-bumpGatewayApi-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.0.0-chore-bumpGatewayApi-SNAPSHOT/gravitee-expression-language-2.0.0-chore-bumpGatewayApi-SNAPSHOT.zip)
=> fix: bump gateway-api as we don't mix rxJava versions

pom.xml
**Issue**
NA
Bump `gravitee-node` to 1.27.3
---
- use it directly by updating your project with version: `1.11.3`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/1.11.3/gravitee-expression-language-1.11.3.zip)
=> chore: bump `gravitee-node` to 1.27.3

pom.xml
**Issue**
N/A
Bump version of gravitee-gateway-api + fix prettier maven plugin
---
- use it directly by updating your project with version: `2.0.1-bump-gateway-api-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.0.1-bump-gateway-api-version-SNAPSHOT/gravitee-expression-language-2.0.1-bump-gateway-api-version-SNAPSHOT.zip)
=> fix: use a release version of gateway-api

pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java
related to APIM-718
* Rename jupiter package into reactive
---
- use it directly by updating your project with version: `2.0.1`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.0.1/gravitee-expression-language-2.0.1.zip)
=> chore: rename 'jupiter' package in 'reactive'

pom.xml
**Issue**
---
- use it directly by updating your project with version: `2.1.1-bump-gateway-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.1.1-bump-gateway-api-SNAPSHOT/gravitee-expression-language-2.1.1-bump-gateway-api-SNAPSHOT.zip)
=> fix(deps): update gateway-api to 2.1.0

.circleci/config.yml, .github/renovate.json
**Issue**
N/A
Update renovate config to merge some dependencies automatically
---
- use it directly by updating your project with version: `2.1.1`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.1.1/gravitee-expression-language-2.1.1.zip)
=> chore: update renovate config to merge some dependencies automatically

pom.xml, src/main/java/io/gravitee/el/spel/SpelExpressionParser.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-231
Use newest cache manager plugin
---
- use it directly by updating your project with version: `2.2.0-archi-231-cache-manager-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.2.0-archi-231-cache-manager-SNAPSHOT/gravitee-expression-language-2.2.0-archi-231-cache-manager-SNAPSHOT.zip)
=> feat: bump gravitee-node to use latest cache plugin

src/main/resources/whitelist, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
base64 encoding is a common EL use case so I want this to be included in the default distribution
---
- use it directly by updating your project with version: `3.2.0-bigmike36c-patch-1-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/3.2.0-bigmike36c-patch-1-SNAPSHOT/gravitee-expression-language-3.2.0-bigmike36c-patch-1-SNAPSHOT.zip)
=> feat: update whitelist to include base64 encoding classes

src/main/java/io/gravitee/el/spel/function/xml/XPathExpressionFactory.java, src/main/java/io/gravitee/el/spel/function/xml/XPathFunction.java, src/test/java/io/gravitee/el/spel/function/xml/XPathTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-6587
Today some EL using XPath are failing because the document builder is configured to be namespace aware but we always force the namespaces as an empty Map. The goal of this pull request is to ease the usage of xpath by disabling this namespace aware configuration.
Next step in the future will be to think about how to extract the namepaces properly and document what kind of EL using XPath are allowed or not using our product. 
=> fix: document builder should not be namespace aware as namespace are not extracted from EL

pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java
**Issue**
BREAKING CHANGE: classes overriding TemplateVariableProvider#provide(ExecutionContext) will be to update the signature https://gravitee.atlassian.net/browse/APIM-7417
---
- use it directly by updating your project with version: `4.0.0-apim-7417-refactor-el-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.0.0-apim-7417-refactor-el-SNAPSHOT/gravitee-expression-language-4.0.0-apim-7417-refactor-el-SNAPSHOT.zip)
=> feat: remove variable provider provide(ctx) method

src/main/java/io/gravitee/el/TemplateEngine.java, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-548
Since the beginning of the v4, we’ve made some evolutions on the 
template engine to support evaluation in a reactive way. At the time, we
decided to deprecate blocking getValue() and convert() methods and force
using the reactive eval() method instead.
We now think that non-reactive evaluation of EL expression can still
make sense when resolving an EL expression outside of the context of an
API call:
It offers better performances when evaluating simple EL expressions.
It allows us to keep simplicity. Especially when you need to evaluate an
EL outside of a reactive chain.
---
🚀 A prerelease version of this package has been published on Gravitee's …
=> feat: allow evaluating EL synchronously

src/main/resources/whitelist
**Issue**
APIM-7509
White list methods used for secret reference `{#secrets.get(...)}`
---
- use it directly by updating your project with version: `4.0.0-APIM-7509-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.0.0-APIM-7509-SNAPSHOT/gravitee-expression-language-4.0.0-APIM-7509-SNAPSHOT.zip)
=> feat: add while list for secrets.get() methods

src/main/java/io/gravitee/el/AbstractSpringFactoriesLoaderTemplateVariableProviderFactory.java, src/test/java/io/gravitee/el/spel/TemplateVariableFactoryTest.java, src/test/resources/META-INF/spring.factories
**Issue**
https://gravitee.atlassian.net/browse/APIM-8416
Changes where made to remove deprecated String API but the replacement was loading new bean instead of the one created by `META-INF/spring.factories` files, hide some `TemplateVariableProvider`. 
---
- use it directly by updating your project with version: `4.0.1-fix-dictionary-el-variable-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.0.1-fix-dictionary-el-variable-SNAPSHOT/gravitee-expression-language-4.0.1-fix-dictionary-el-variable-S …
=> fix: template variable discovery failed to find them all

pom.xml
`json-path` library is still not updated to use the fixed version of `json-smart`. This commit defines explicitly the `json-smart` library to force the use of 2.5.2.
---
- use it directly by updating your project with version: `4.0.3-override-json-smart-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.0.3-override-json-smart-version-SNAPSHOT/gravitee-expression-language-4.0.3-override-json-smart-version-SNAPSHOT.zip)
=> fix(deps): define json-smart dependency to force version 2.5.2

src/main/resources/whitelist
This will prevent the WARN logs during APIM start
```
The EL whitelisted declaration [method io.gravitee.secrets.api.el.DelegatingEvaluatedSecretsMethods get java.lang.String java.lang.String] cannot be loaded. Message is [java.lang.NoSuchMethodException: io.gravitee.secrets.api.el.DelegatingEvaluatedSecretsMethods.get(java.lang.String,java.lang.String)]
```
---
- use it directly by updating your project with version: `4.0.4-fix-whitelist-secret-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.0. …
=> fix: define the correct method in whitelist

pom.xml, src/main/java/io/gravitee/el/spel/context/SpelTemplateContext.java, src/main/java/io/gravitee/el/spel/function/xml/escape/XmlEscapeFunction.java, src/test/java/io/gravitee/el/spel/function/xml/escape/XmlEscapeFunctionTest.java
**Issue**
https://gravitee.atlassian.net/browse/PEN-30
Introduce `XmlEscapeFunction` to safely escape XML special characters and prevent injection vulnerabilities. Includes integration with the EL engine and comprehensive unit tests.
---
- use it directly by updating your project with version: `4.2.0-pen-30-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.2.0-pen-30-SNAPSHOT/gravitee-expression-language-4.2.0-pen-30-SNAPSHOT.zip)
=> feat: Add `XmlEscapeFunction` for XML content escaping
