gravitee-io/gravitee-expression-language

pom.xml, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/jmh/ReplaceAllBenchmark.java, src/test/java/io/gravitee/el/spel/jmh/ReplaceAllBenchmarkTest.java
Closes gravitee-io/issues#1902
=> fix(expression-language): Improve expression language performance

pom.xml, src/main/java/io/gravitee/el/TemplateEngine.java, src/main/java/io/gravitee/el/TemplateVariableProvider.java, src/test/java/io/gravitee/el/spel/SpelTemplateEngineTest.java
And move dependency to Gravitee EL
Closes gravitee-io/issues#1987
=> chore: Remove deprecated Gateway EL module

pom.xml, src/main/java/io/gravitee/el/spel/function/JsonPathFunction.java, src/test/java/io/gravitee/el/spel/JsonPathTest.java
Closes gravitee-io/issues#1713
=> fix(jsonpath): Do not use internal cache

src/main/java/io/gravitee/el/exceptions/ELNullEvaluationException.java
=> fix(spel): manage null result

pom.xml, src/main/java/io/gravitee/el/ExpressionLanguageInitializer.java, src/main/java/io/gravitee/el/exceptions/ExpressionEvaluationException.java, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/main/java/io/gravitee/el/spel/context/SecuredEvaluationContext.java, src/main/java/io/gravitee/el/spel/context/SecuredMethodResolver.java, src/main/java/io/gravitee/el/spel/context/SpelTemplateContext.java, src/main/resources/whitelist, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java, src/test/resources/logback-test.xml
Closes gravitee-io/issues#3660
=> feat(el): sandbox EL to whitelisted methods

src/main/java/io/gravitee/el/spel/context/SecuredMethodResolver.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
Closes gravitee-io/issues#4003
=> fix(sandbox-init): better initialization and configuration handling

src/main/java/io/gravitee/el/ExpressionLanguageInitializer.java, src/main/java/io/gravitee/el/exceptions/ExpressionEvaluationException.java, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/main/java/io/gravitee/el/spel/context/SecuredContructorResolver.java, src/main/java/io/gravitee/el/spel/context/SecuredEvaluationContext.java, src/main/java/io/gravitee/el/spel/context/SecuredMethodResolver.java, src/main/java/io/gravitee/el/spel/context/SecuredResolver.java, src/main/resources/whitelist, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
=> feat(expression-language): add possibility to allow constructors in EL

src/main/java/io/gravitee/el/spel/context/SecuredMethodResolver.java
=> feat(management): expose SecuredMethodResolver+getMethods as public

pom.xml, src/main/java/io/gravitee/el/spel/context/SpelTemplateContext.java, src/main/java/io/gravitee/el/spel/function/json/JsonPathFunction.java, src/main/java/io/gravitee/el/spel/function/xml/DocumentBuilderFactoryUtils.java, src/main/java/io/gravitee/el/spel/function/xml/XPathEvaluationType.java, src/main/java/io/gravitee/el/spel/function/xml/XPathException.java, src/main/java/io/gravitee/el/spel/function/xml/XPathExpression.java, src/main/java/io/gravitee/el/spel/function/xml/XPathExpressionFactory.java, src/main/java/io/gravitee/el/spel/function/xml/XPathFunction.java, src/main/java/io/gravitee/el/spel/function/xml/XPathParseException.java, src/main/java/io/gravitee/el/spel/function/xml/XmlPayloadConverter.java, src/test/java/io/gravitee/el/spel/function/xml/XPathTest.java
Closes gravitee-io/issues#5670
=> chore: Remove spring-integration dependency

.circleci/config.yml, pom.xml, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
Closes gravitee-io/issues#5938
=> fix(el): Allow spaces before expression

src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
=> fix: resolve evalution with any white space char

pom.xml, src/main/java/io/gravitee/el/spel/context/HttpHeadersPropertyAccessor.java, src/main/java/io/gravitee/el/spel/context/SecuredEvaluationContext.java, src/test/java/io/gravitee/el/spel/EvaluableRequest.java, src/test/java/io/gravitee/el/spel/Request.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
Closes gravitee-io/issues#6772
=> feat(headers): Internal rework and introduce HTTP Headers API

src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
=> test: add evaluation cases to ensure compatibility

pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java
**Issue**
https://github.com/gravitee-io/issues/issues/8229
=> refactor: use higher level HttpExecutionContext for TemplateProvider

pom.xml
**Issue**
---
- use it directly by updating your project with version: `2.1.0-chore-bump-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.1.0-chore-bump-version-SNAPSHOT/gravitee-expression-language-2.1.0-chore-bump-version-SNAPSHOT.zip)
=> Chore bump version

pom.xml
**Issue**
---
- use it directly by updating your project with version: `2.1.0-upgrade-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/2.1.0-upgrade-deps-SNAPSHOT/gravitee-expression-language-2.1.0-upgrade-deps-SNAPSHOT.zip)
=> fix(deps): upgrade gravitee-bom & gravitee-common

CHANGELOG.md, pom.xml, src/main/java/io/gravitee/el/TemplateVariableProvider.java
=> Merge alpha in master

src/main/java/io/gravitee/el/spel/SpelExpressionParser.java
https://gravitee.atlassian.net/browse/APIM-2193
---
- use it directly by updating your project with version: `3.1.0-apim-2193-hc-el-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/3.1.0-apim-2193-hc-el-SNAPSHOT/gravitee-expression-language-3.1.0-apim-2193-hc-el-SNAPSHOT.zip)
=> Add access to the EL parser for further customization

.github/renovate.json, pom.xml
Manual update of some dependencies
---
- use it directly by updating your project with version: `3.2.2-bump-dependencies-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/3.2.2-bump-dependencies-SNAPSHOT/gravitee-expression-language-3.2.2-bump-dependencies-SNAPSHOT.zip)
=> Update some dependencies

src/main/java/io/gravitee/el/exceptions/ExpressionEvaluationException.java, src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java, src/test/java/io/gravitee/el/spel/context/SpelTemplateEngineTest.java
**Issue**
---
- use it directly by updating your project with version: `4.1.1-APIM-9992-logs-trace-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el/gravitee-expression-language/4.1.1-APIM-9992-logs-trace-SNAPSHOT/gravitee-expression-language-4.1.1-APIM-9992-logs-trace-SNAPSHOT.zip)
=> fix: update error handling
